# GitHub identity
owner: delaysystem
repo: delaysystem.github.io
assignees:
  - delaysystem

# Endpoints to monitor
sites:
  - name: TuBot Panel
    url: https://panel.tubot.lat
  - name: TuBot API
    url: https://api.tubot.lat

# Status website settings
status-website:
  name: System Status
  # Use custom domain if you have one, or set baseUrl if using github.io
  cname: status.tubot.lat
  theme: dark

navbar:
    - title: "Home"
      href: "https://tubot.lat"

  # Subheading text displayed directly below the header
  introTitle: "Real-time System Performance"
  introMessage: "Welcome to our live service status page. Current and historical uptime telemetry is tracked below."
